# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otterscope < Formula
  desc "Lightweight, self-hosted observability and evals for AI agents"
  homepage "https://github.com/otterscope/otterscope"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/otterscope/otterscope/releases/download/v0.1.1/otterscope_0.1.1_darwin_amd64.tar.gz"
      sha256 "9ff791d704003769dbdb8d23317d5975bae627da685ce8402b416383f0a23c77"

      define_method(:install) do
        bin.install "otterscope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/otterscope/otterscope/releases/download/v0.1.1/otterscope_0.1.1_darwin_arm64.tar.gz"
      sha256 "811104e1c7f35eeee2480f854acb7a73ee28414522fdf95f3283257127867b5f"

      define_method(:install) do
        bin.install "otterscope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/otterscope/otterscope/releases/download/v0.1.1/otterscope_0.1.1_linux_amd64.tar.gz"
      sha256 "b109095753a3389a2f5d8caa7ea9abff76327bc94ab6dcf7e0c18ee3b81043e7"
      define_method(:install) do
        bin.install "otterscope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/otterscope/otterscope/releases/download/v0.1.1/otterscope_0.1.1_linux_arm64.tar.gz"
      sha256 "f63c7e7e84391f89d2ad99ed59da0f9502864ccd2f72db0aaeffe78f28ff4cb1"
      define_method(:install) do
        bin.install "otterscope"
      end
    end
  end

  test do
    system "#{bin}/otterscope", "version"
  end
end
